"""Radiologist-defined alias dictionary for chest radiology findings.

Each label maps to a list of phrase aliases plus optional exclude phrases.
There are 49 labels in this dictionary. To extend it, add a new
entry below or pass your own dict to ``label_reports`` / ``label_study``.

Schema::

    ALIASES = {
        "<label_key>": {
            "aliases": [<phrase>, ...],   # required, >= 1 phrase
            "exclude": [<phrase>, ...],   # optional, vetoes a hit if present
        },
        ...
    }

Use ``radlabels.LABEL_NAMES`` for a sorted list of label keys.
"""

from __future__ import annotations

ALIAS_VERSION = "1.0"

ALIASES: dict[str, dict[str, list[str]]] = {
    "acute_rib_fracture": {
        "aliases": [
            "acute rib fracture",
            "new rib fracture",
            "recent rib fracture",
            "displaced rib fracture",
            "nondisplaced rib fracture",
            "non-displaced rib fracture",
            "minimally displaced rib fracture",
            "acute rib fractures",
        ],
        "exclude": [],
    },
    "air_space_opacity": {
        "aliases": [
            "consolidation",
            "infiltrate",
            "pneumonia",
            "airspace disease",
            "airspace opacity",
            "air space disease",
            "air space opacity",
            "air-space disease",
            "air-space opacity",
            "groundglass opacity",
            "ground-glass opacity",
            "ground glass opacity",
            "ground glass opacities",
            "ground-glass opacities",
            "patchy opacity",
            "patchy opacities",
            "confluent opacity",
            "confluent opacities",
            "alveolar opacity",
            "alveolar opacities",
            "alveolar infiltrate",
            "parenchymal opacity",
            "airspace infiltrate",
            "airspace process",
            "parenchymal infiltrate",
            "focal consolidation",
            "lobar consolidation",
            "patchy consolidation",
            "dense consolidation",
            "pneumonic infiltrate",
            "pneumonic consolidation",
            "bronchopneumonia",
        ],
        "exclude": [],
    },
    "atelectasis": {
        "aliases": [
            "atelectasis",
            "atelectatic",
            "atelectatic lung",
            "lung collapse",
            "collapsed lung",
            "linear atelectasis",
            "discoid atelectasis",
            "plate atelectasis",
            "plate-like atelectasis",
            "platelike atelectasis",
            "bandlike atelectasis",
            "band-like atelectasis",
            "streaky atelectasis",
            "bibasilar atelectasis",
            "basilar atelectasis",
            "bilateral atelectasis",
            "scarring atelectasis",
            "compressive atelectasis",
            "relaxation atelectasis",
            "passive atelectasis",
            "rounded atelectasis",
        ],
        "exclude": [],
    },
    "bronchial_wall_thickening": {
        "aliases": [
            "bronchial wall thickening",
            "bronchial thickening",
            "airway wall thickening",
            "airway thickening",
            "thickened bronchial walls",
            "thickened airway walls",
            "bronchial wall thickened",
        ],
        "exclude": [],
    },
    "bullous_disease": {
        "aliases": [
            "bullous changes",
            "bullous change",
            "pulmonary bullae",
            "pulmonary bulla",
            "bullae",
            "bullous emphysema",
            "giant bulla",
            "giant bullae",
            "bullous lung disease",
            "apical bullae",
            "apical bulla",
            "subpleural bullae",
            "subpleural bulla",
        ],
        "exclude": [],
    },
    "calcification_of_the_aorta": {
        "aliases": [
            "aortic calcification",
            "calcified aorta",
            "atherosclerotic calcification",
            "atherosclerotic aortic calcification",
            "aortic atherosclerosis",
            "aortic knob calcification",
        ],
        "exclude": [],
    },
    "cardiomegaly": {
        "aliases": [
            "cardiomegaly",
            "enlarged heart",
            "heart enlarged",
            "cardiac enlargement",
            "cardiac silhouette enlargement",
            "heart enlargement",
            "increased cardiac",
            "increased heart size",
            "enlarged cardiac silhouette",
            "enlarged cardiomediastinal silhouette",
            "dilated heart",
            "cardiac hypertrophy",
            "globular heart",
            "large heart",
            "large cardiac silhouette",
            "cardiac silhouette enlarged",
            "heart size enlarged",
            "prominent cardiac silhouette",
        ],
        "exclude": [],
    },
    "central_venous_catheter": {
        "aliases": [
            "central venous catheter",
            "central line",
            "cvc",
            "picc line",
            "picc",
            "peripherally inserted central catheter",
            "subclavian line",
            "internal jugular line",
            "tunneled catheter",
            "hickman catheter",
            "port-a-cath",
            "portacath",
            "implanted port",
            "mediport",
            "triple lumen catheter",
            "swan-ganz catheter",
            "pulmonary artery catheter",
        ],
        "exclude": [],
    },
    "consolidation": {
        "aliases": [
            "consolidation",
            "focal consolidation",
            "lobar consolidation",
            "patchy consolidation",
            "dense consolidation",
            "pneumonic consolidation",
            "consolidative opacity",
        ],
        "exclude": [],
    },
    "emphysema": {
        "aliases": [
            "emphysema",
            "centrilobular emphysema",
            "paraseptal emphysema",
            "panlobular emphysema",
            "emphysematous changes",
            "copd emphysema",
        ],
        "exclude": [],
    },
    "endotracheal_tube": {
        "aliases": [
            "endotracheal tube",
            "et tube",
            "ett",
            "endotracheal intubation",
            "tracheal tube",
            "endotracheal cannula",
        ],
        "exclude": [],
    },
    "enlarged_cardiomediastinum": {
        "aliases": [
            "enlarged cardiomediastinum",
            "enlarged cardiomediastinal silhouette",
            "widened mediastinum",
            "mediastinal widening",
            "mediastinal enlargement",
            "prominent mediastinum",
            "prominent mediastinal silhouette",
        ],
        "exclude": [],
    },
    "enteric_tube": {
        "aliases": [
            "enteric tube",
            "nasogastric tube",
            "ng tube",
            "orogastric tube",
            "og tube",
            "dobhoff tube",
            "feeding tube",
            "gastric tube",
        ],
        "exclude": [],
    },
    "fracture_generic": {
        "aliases": [
            "fracture",
            "fractures",
            "osseous fracture",
            "clavicle fracture",
            "clavicular fracture",
            "humerus fracture",
            "humeral fracture",
            "scapular fracture",
            "sternal fracture",
            "vertebral fracture",
            "compression fracture",
        ],
        "exclude": [],
    },
    "ground_glass_opacity": {
        "aliases": [
            "ground glass opacity",
            "ground-glass opacity",
            "groundglass opacity",
            "ground glass opacities",
            "ground-glass opacities",
            "ground glass pattern",
            "ground glass infiltrate",
            "ground glass infiltrates",
            "ground glass nodule",
            "ground glass",
            "hazy opacity",
            "hazy opacities",
        ],
        "exclude": [],
    },
    "hiatus_hernia": {
        "aliases": [
            "hiatal hernia",
            "hiatus hernia",
            "paraesophageal hernia",
            "para-esophageal hernia",
            "gastric hernia",
            "sliding hiatal hernia",
            "large hiatal hernia",
            "small hiatal hernia",
            "retrocardiac hiatal hernia",
            "hernia hiatus",
        ],
        "exclude": [],
    },
    "hilar_lymphadenopathy": {
        "aliases": [
            "hilar adenopathy",
            "hilar lymphadenopathy",
            "enlarged hilar nodes",
            "enlarged hilar lymph nodes",
            "hilar lymph node enlargement",
            "prominent hilar nodes",
            "prominent hilar lymph nodes",
            "bulky hilar nodes",
            "bulky hila",
            "bulky hilum",
            "lymphadenopathy hilum",
            "adenopathy hilum",
            "hilar mass",
            "bilateral hilar adenopathy",
        ],
        "exclude": [
            "mediastinal adenopathy",
            "mediastinal lymphadenopathy",
        ],
    },
    "hyperinflation": {
        "aliases": [
            "hyperexpanded",
            "hyperexpansion",
            "hyperinflated",
            "hyperinflation",
            "increased lung volume",
            "increased lung volumes",
            "overinflated lungs",
            "overinflation",
            "overexpanded",
            "hyperaeration",
            "hyperaerated",
            "barrel chest",
            "flattened diaphragm",
            "flattened diaphragms",
            "flattened hemidiaphragm",
            "flattened hemidiaphragms",
            "flattening diaphragm",
            "flattening hemidiaphragms",
            "low flat diaphragms",
            "lung hyperexpansion",
        ],
        "exclude": [],
    },
    "implantable_electronic_device": {
        "aliases": [
            "spinal cord stimulator",
            "neurostimulator",
            "nerve stimulator",
            "pain pump",
            "medicine pump",
            "intrathecal pump",
            "infusion pump",
            "loop recorder",
            "implantable loop recorder",
            "dorsal column stimulator",
            "vagal nerve stimulator",
            "vagus nerve stimulator",
            "deep brain stimulator",
            "phrenic nerve stimulator",
        ],
        "exclude": [],
    },
    "infiltration": {
        "aliases": [
            "infiltrate",
            "infiltrates",
            "pulmonary infiltrate",
            "alveolar infiltrate",
            "interstitial infiltrate",
            "airspace infiltrate",
            "parenchymal infiltrate",
        ],
        "exclude": [],
    },
    "intercostal_drain": {
        "aliases": [
            "pleural drain",
            "pleural tube",
            "chest tube",
            "chest tubes",
            "chest drain",
            "chest drains",
            "intercostal tube",
            "intercostal drain",
            "thoracostomy tube",
            "thoracotomy tube",
            "thoracotomy drain",
            "thracostomy drain",
            "pigtail catheter",
            "pigtail drain",
            "pleurx catheter",
            "tunneled pleural catheter",
        ],
        "exclude": [],
    },
    "interstitial_thickening": {
        "aliases": [
            "interstitial markings",
            "reticular markings",
            "reticular pattern",
            "reticulonodular pattern",
            "reticulonodular markings",
            "interstitial pattern",
            "interstitial changes",
            "septal thickening",
            "septal lines",
            "kerley lines",
            "kerley b lines",
            "thickened interstitium",
            "thickening interstitium",
            "prominent interstitium",
            "interstitial prominence",
            "interstitial prominence lungs",
            "crazy paving",
            "honeycombing",
            "fibrosis interstitial",
        ],
        "exclude": [],
    },
    "lobar_segmental_collapse": {
        "aliases": [
            "lobar atelectasis",
            "lobar collapse",
            "segmental atelectasis",
            "segmental collapse",
            "subsegmental atelectasis",
            "subsegmental collapse",
            "segment atelectasis",
            "atelectasis segment",
            "right lower lobe atelectasis",
            "right middle lobe atelectasis",
            "right upper lobe atelectasis",
            "left upper lobe atelectasis",
            "left lower lobe atelectasis",
            "right lower lobe collapse",
            "right middle lobe collapse",
            "right upper lobe collapse",
            "left upper lobe collapse",
            "left lower lobe collapse",
            "lingular atelectasis",
            "lingula atelectasis",
            "lingular collapse",
            "lingula collapse",
            "rll atelectasis",
            "rml atelectasis",
            "rul atelectasis",
            "lll atelectasis",
            "lul atelectasis",
            "rll collapse",
            "rml collapse",
            "rul collapse",
            "lll collapse",
            "lul collapse",
        ],
        "exclude": [],
    },
    "lung_lesion": {
        "aliases": [
            "lung lesion",
            "pulmonary lesion",
            "parenchymal lesion",
            "cavitary lesion",
            "lytic lesion",
            "cavitation",
        ],
        "exclude": [],
    },
    "lung_nodule_or_mass": {
        "aliases": [
            "lung nodule",
            "lung nodules",
            "pulmonary nodule",
            "pulmonary nodules",
            "lung mass",
            "pulmonary mass",
            "parenchymal mass",
            "parenchymal nodule",
            "nodular opacity",
            "nodular density",
            "granuloma",
            "calcified granuloma",
            "calcified nodule",
            "noncalcified nodule",
            "solitary pulmonary nodule",
            "solitary nodule",
            "lung lesion",
            "pulmonary lesion",
            "lung tumor",
            "pulmonary tumor",
            "coin lesion",
        ],
        "exclude": [],
    },
    "lung_opacity": {
        "aliases": [
            "lung opacity",
            "lung opacities",
            "pulmonary opacity",
            "pulmonary opacities",
            "parenchymal opacity",
            "focal opacity",
            "diffuse opacity",
            "patchy opacity",
        ],
        "exclude": [],
    },
    "non_acute_rib_fracture": {
        "aliases": [
            "healed rib fracture",
            "healed rib fractures",
            "old rib fracture",
            "old rib fractures",
            "chronic rib fracture",
            "chronic rib fractures",
            "subacute rib fracture",
            "healing rib fracture",
            "distant rib fracture",
            "rib fracture callus",
            "callus rib fracture",
            "remote rib fracture",
            "remote rib fractures",
            "prior rib fracture",
            "prior rib fractures",
        ],
        "exclude": [],
    },
    "nonsurgical_internal_foreign_body": {
        "aliases": [
            "foreign body",
            "foreign bodies",
            "ingested foreign body",
            "aspirated foreign body",
            "retained foreign body",
            "coin",
            "swallowed coin",
            "ingested object",
            "swallowed object",
            "retained bullet",
            "retained bullets",
            "retained metal fragment",
            "metallic foreign body",
            "metallic fragment",
            "shrapnel",
            "bb pellet",
            "bb pellets",
            "bullet fragment",
            "bullet fragments",
            "fish bone",
            "chicken bone",
            "animal bone",
            "quarter",
            "penny",
            "dime",
            "nickel",
            "button battery",
            "retained BB",
            "retained BBs",
        ],
        "exclude": [],
    },
    "other_hernia": {
        "aliases": [
            "diaphragmatic hernia",
            "bochdalek hernia",
            "morgagni hernia",
            "abdominal hernia",
        ],
        "exclude": [
            "hiatal hernia",
            "hiatus hernia",
        ],
    },
    "pacemaker_electronic_cardiac_device_or_wires": {
        "aliases": [
            "pacemaker",
            "dual chamber pacemaker",
            "single chamber pacemaker",
            "biventricular pacemaker",
            "AICD",
            "CRT",
            "CRT-D",
            "CRT-P",
            "ICD",
            "pacer",
            "defibrillator",
            "implantable defibrillator",
            "implantable cardioverter defibrillator",
            "cardioverter defibrillator",
            "pacing leads",
            "pacing lead",
            "pacemaker leads",
            "pacemaker lead",
            "pacing wires",
            "pacing wire",
            "pacemaker wires",
            "pacemaker wire",
            "epicardial pacing wires",
            "epicardial pacing wire",
            "transvenous pacing lead",
            "leadless pacemaker",
        ],
        "exclude": [],
    },
    "peribronchial_cuffing": {
        "aliases": [
            "peribronchial cuffing",
            "peribronchial thickening",
            "peribronchial markings",
            "peribronchial prominence",
            "bronchial cuffing",
            "donut sign",
        ],
        "exclude": [],
    },
    "pleural_effusion": {
        "aliases": [
            "pleural effusion",
            "pleural fluid",
            "pleural collection",
            "hemothorax",
            "empyema",
            "hydrothorax",
            "fluid pleural space",
            "loculated effusion",
            "bilateral effusions",
            "layering effusion",
            "free flowing effusion",
            "free-flowing effusion",
            "simple effusion",
            "complex effusion",
            "small effusion",
            "moderate effusion",
            "large effusion",
            "trace effusion",
            "tiny effusion",
            "blunting costophrenic angle",
            "costophrenic blunting",
            "blunted costophrenic angle",
            "layering pleural",
            "meniscus sign",
        ],
        "exclude": [
            "pericardial effusion",
        ],
    },
    "pleural_other": {
        "aliases": [
            "pleural abnormality",
            "pleural disease",
            "pleural lesion",
            "pleural mass",
            "pleural calcification",
            "calcified pleura",
        ],
        "exclude": [],
    },
    "pleural_thickening": {
        "aliases": [
            "pleural thickening",
            "thickened pleura",
            "pleural plaque",
            "pleural plaques",
            "calcified pleural plaque",
            "apical pleural thickening",
            "pleural scarring",
        ],
        "exclude": [],
    },
    "pneumomediastinum": {
        "aliases": [
            "pneumomediastinum",
            "mediastinal air",
            "mediastinal emphysema",
            "air in the mediastinum",
            "pneumopericardium",
        ],
        "exclude": [],
    },
    "pneumonia": {
        "aliases": [
            "pneumonia",
            "bronchopneumonia",
            "atypical pneumonia",
            "lobar pneumonia",
            "bacterial pneumonia",
            "viral pneumonia",
            "aspiration pneumonia",
            "infectious process",
            "infection",
            "pneumonic infiltrate",
        ],
        "exclude": [],
    },
    "pneumoperitoneum": {
        "aliases": [
            "pneumoperitoneum",
            "free intraperitoneal air",
            "free abdominal air",
            "free air under the diaphragm",
            "subdiaphragmatic free air",
            "intraperitoneal free air",
        ],
        "exclude": [],
    },
    "pneumothorax": {
        "aliases": [
            "pneumothorax",
            "ptx",
            "air pleural space",
            "pleural air",
            "hydropneumothorax",
            "tension pneumothorax",
            "apical pneumothorax",
            "small pneumothorax",
            "large pneumothorax",
            "residual pneumothorax",
            "loculated pneumothorax",
            "basilar pneumothorax",
        ],
        "exclude": [
            "pneumomediastinum",
            "pneumoperitoneum",
        ],
    },
    "pulmonary_artery_enlargement": {
        "aliases": [
            "enlarged pulmonary arteries",
            "pulmonary artery dilation",
            "pulmonary artery dilatation",
            "prominent hilar vessels",
            "pulmonary artery enlargement",
            "dilated pulmonary artery",
            "dilated pulmonary arteries",
            "enlarged pulmonary artery",
            "prominent pulmonary arteries",
            "prominent pulmonary artery",
            "pulmonary arterial enlargement",
            "hilar vessel prominence",
            "enlarged hilar vessels",
            "pulmonary trunk dilation",
            "pulmonary trunk dilatation",
            "pulmonary trunk enlargement",
            "pulmonary trunk prominence",
            "main pulmonary artery enlargement",
            "main pulmonary artery prominence",
            "central pulmonary artery enlargement",
        ],
        "exclude": [],
    },
    "pulmonary_congestion_pulmonary_venous_congestion": {
        "aliases": [
            "congestion",
            "pulmonary congestion",
            "pulmonary venous congestion",
            "pvc",
            "interstitial edema",
            "interstitial pulmonary edema",
            "pulmonary edema",
            "pulmonary interstitial edema",
            "perihilar edema",
            "vascular redistribution",
            "vascular engorgement",
            "vascular congestion",
            "cephalization",
            "cephalization pulmonary vasculature",
            "upper zone redistribution",
            "upper lobe redistribution",
            "prominent pulmonary vasculature",
            "increased pulmonary vasculature",
            "cardiogenic pulmonary edema",
        ],
        "exclude": [],
    },
    "pulmonary_edema": {
        "aliases": [
            "pulmonary edema",
            "pulmonary oedema",
            "interstitial pulmonary edema",
            "alveolar pulmonary edema",
            "cardiogenic pulmonary edema",
            "flash pulmonary edema",
            "acute pulmonary edema",
            "fluid overload",
        ],
        "exclude": [
            "peripheral edema",
        ],
    },
    "pulmonary_fibrosis": {
        "aliases": [
            "pulmonary fibrosis",
            "lung fibrosis",
            "fibrotic change",
            "fibrotic changes",
            "fibrosis",
            "fibrotic scarring",
            "fibrotic band",
            "fibrotic bands",
            "pleuroparenchymal tract",
            "pleuroparenchymal tracts",
            "pleuroparenchymal changes",
            "pleuroparenchymal change",
            "honeycombing",
            "honeycomb lung",
            "usual interstitial pneumonia",
        ],
        "exclude": [],
    },
    "shoulder_dislocation": {
        "aliases": [
            "glenohumeral joint dislocation",
            "glenohumeral dislocation",
            "shoulder dislocation",
            "shoulder is dislocated",
            "shoulder dislocated",
            "shoulder subluxation",
            "glenohumeral subluxation",
            "dislocation shoulder",
            "dislocation glenohumeral",
            "humeral head dislocation",
            "humerus dislocation",
            "humeral head subluxed",
            "humeral head subluxation",
            "anterior shoulder dislocation",
            "posterior shoulder dislocation",
            "inferior shoulder dislocation",
            "anteriorly dislocated shoulder",
            "posteriorly dislocated shoulder",
            "dislocated humeral head",
        ],
        "exclude": [],
    },
    "subcutaneous_emphysema": {
        "aliases": [
            "subcutaneous emphysema",
            "subcutaneous gas",
            "subcutaneous air",
            "soft tissue emphysema",
            "soft tissue gas",
            "soft tissue air",
            "gas soft tissues",
            "emphysema soft tissues",
            "chest wall emphysema",
            "chest wall gas",
            "chest wall air",
            "subq emphysema",
            "subq air",
            "extensive subcutaneous emphysema",
            "extensive subcutaneous air",
            "subcutaneous emphysema chest wall",
        ],
        "exclude": [],
    },
    "support_devices_generic": {
        "aliases": [
            "support device",
            "support devices",
            "hardware",
            "monitoring device",
            "lines and tubes",
            "tubes and lines",
        ],
        "exclude": [],
    },
    "tortuous_aorta": {
        "aliases": [
            "tortuous aorta",
            "aortic tortuosity",
            "ectatic aorta",
            "aortic ectasia",
            "aortic elongation",
            "elongated aorta",
            "aorta is elongated",
            "unfolded aorta",
            "unfolding of the aorta",
            "unfolding aorta",
        ],
        "exclude": [],
    },
    "tracheal_deviation": {
        "aliases": [
            "tracheal deviation",
            "trachea deviated",
            "deviated trachea",
            "shifted trachea",
            "trachea shifted",
            "leftward trachea",
            "rightward trachea",
            "leftward tracheal deviation",
            "rightward tracheal deviation",
            "displaced trachea",
            "trachea displaced",
            "mass effect trachea",
            "tracheal shift",
            "shift trachea",
            "midline shift trachea",
        ],
        "exclude": [],
    },
    "tracheostomy_tube": {
        "aliases": [
            "tracheostomy tube",
            "tracheostomy",
            "trach tube",
            "trach",
        ],
        "exclude": [],
    },
    "whole_lung_or_majority_collapse": {
        "aliases": [
            "complete right side atelectasis",
            "total right lung collapse",
            "complete left side atelectasis",
            "total left lung collapse",
            "complete lung collapse",
            "complete lung atelectasis",
            "total lung collapse",
            "total lung atelectasis",
            "whole lung collapse",
            "whole lung atelectasis",
            "entire lung collapse",
            "entire lung atelectasis",
            "complete right lung collapse",
            "complete left lung collapse",
            "whole right lung collapse",
            "whole left lung collapse",
            "entire right lung collapse",
            "entire left lung collapse",
            "collapsed lung",
            "collapse entire lung",
            "collapse whole lung",
        ],
        "exclude": [],
    },
}

LABEL_NAMES: list[str] = sorted(ALIASES.keys())

# ---------------------------------------------------------------------------
# Two-level taxonomy: leaf label → parent group.
# Derived from Table 8 in Delbrouck et al. (2026).  Parent labels (the values)
# are not in ALIASES and carry no aliases of their own; they are derived
# automatically from their children at label-compilation time.
# ---------------------------------------------------------------------------
PARENT_MAP: dict[str, str] = {
    # pulmonary_abnormality
    "air_space_opacity": "pulmonary_abnormality",
    "atelectasis": "pulmonary_abnormality",
    "consolidation": "pulmonary_abnormality",
    "ground_glass_opacity": "pulmonary_abnormality",
    "pneumonia": "pulmonary_abnormality",
    "bullous_disease": "pulmonary_abnormality",
    "emphysema": "pulmonary_abnormality",
    "hyperinflation": "pulmonary_abnormality",
    "infiltration": "pulmonary_abnormality",
    "interstitial_thickening": "pulmonary_abnormality",
    "lobar_segmental_collapse": "pulmonary_abnormality",
    "lung_lesion": "pulmonary_abnormality",
    "lung_nodule_or_mass": "pulmonary_abnormality",
    "lung_opacity": "pulmonary_abnormality",
    "pulmonary_edema": "pulmonary_abnormality",
    "pulmonary_fibrosis": "pulmonary_abnormality",
    "whole_lung_or_majority_collapse": "pulmonary_abnormality",
    # pleural_abnormality
    "pleural_effusion": "pleural_abnormality",
    "pleural_other": "pleural_abnormality",
    "pleural_thickening": "pleural_abnormality",
    "pneumothorax": "pleural_abnormality",
    # cardiomediastinal_abnormality
    "calcification_of_the_aorta": "cardiomediastinal_abnormality",
    "cardiomegaly": "cardiomediastinal_abnormality",
    "enlarged_cardiomediastinum": "cardiomediastinal_abnormality",
    "pulmonary_artery_enlargement": "cardiomediastinal_abnormality",
    "pulmonary_congestion_pulmonary_venous_congestion": "cardiomediastinal_abnormality",
    "tortuous_aorta": "cardiomediastinal_abnormality",
    # airway_abnormality
    "bronchial_wall_thickening": "airway_abnormality",
    "peribronchial_cuffing": "airway_abnormality",
    "tracheal_deviation": "airway_abnormality",
    # hilar_abnormality
    "hilar_lymphadenopathy": "hilar_abnormality",
    # fracture_or_trauma
    "acute_rib_fracture": "fracture_or_trauma",
    "fracture_generic": "fracture_or_trauma",
    "non_acute_rib_fracture": "fracture_or_trauma",
    "shoulder_dislocation": "fracture_or_trauma",
    "subcutaneous_emphysema": "fracture_or_trauma",
    # mediastinal_or_abdominal_air
    "pneumomediastinum": "mediastinal_or_abdominal_air",
    "pneumoperitoneum": "mediastinal_or_abdominal_air",
    # hernia_abnormality
    "hiatus_hernia": "hernia_abnormality",
    "other_hernia": "hernia_abnormality",
    # support_devices
    "central_venous_catheter": "support_devices",
    "endotracheal_tube": "support_devices",
    "enteric_tube": "support_devices",
    "implantable_electronic_device": "support_devices",
    "intercostal_drain": "support_devices",
    "nonsurgical_internal_foreign_body": "support_devices",
    "pacemaker_electronic_cardiac_device_or_wires": "support_devices",
    "support_devices_generic": "support_devices",
    "tracheostomy_tube": "support_devices",
}
